import path from 'path';

const EXPORT_FILEPATH = path.join(__dirname, './tmp/exportSpace');

const DEFAULT_GLOBAL_TIMEOUT = 270000;
const TOOLTIP_FADE_OUT_PAUSE = 10000;
const INPUT_TYPE_PAUSE = 2000;
const VISIT_SPACE_PAUSE = 5000;
const OPEN_SAVED_SPACE_PAUSE = 2000;
const LOAD_SPACE_PAUSE = 2000;
const EXPORT_SPACE_PAUSE = 2000;
const DELETE_SPACE_PAUSE = 2000;
const SAVE_SPACE_PAUSE = 15000;
const LOAD_TAB_PAUSE = 2000;
const OPEN_DRAWER_PAUSE = 1000;

export {
  DEFAULT_GLOBAL_TIMEOUT,
  EXPORT_FILEPATH,
  TOOLTIP_FADE_OUT_PAUSE,
  INPUT_TYPE_PAUSE,
  VISIT_SPACE_PAUSE,
  OPEN_SAVED_SPACE_PAUSE,
  LOAD_SPACE_PAUSE,
  EXPORT_SPACE_PAUSE,
  DELETE_SPACE_PAUSE,
  SAVE_SPACE_PAUSE,
  LOAD_TAB_PAUSE,
  OPEN_DRAWER_PAUSE,
};
