export const GET_SPACE = 'GET_SPACE';
export const GET_SPACES = 'GET_SPACES';
export const FLAG_GETTING_SPACE = 'FLAG_GETTING_SPACE';
export const FLAG_LOADING_SPACE = 'FLAG_LOADING_SPACE';
export const FLAG_GETTING_SPACES = 'FLAG_GETTING_SPACES';
export const TOGGLE_SPACE_MENU = 'TOGGLE_SPACE_MENU';
export const CLEAR_SPACE = 'CLEAR_SPACE';
export const ON_GET_SPACE_SUCCESS = 'ON_GET_SPACE_SUCCESS';
