FROM mhart/alpine-node:10

RUN mkdir -p /usr/src/app
WORKDIR /usr/src/app

# install app dependencies
COPY package.json /usr/src/app/
RUN yarn install

# setup before linting
RUN yarn setup

# bundle app source
COPY . /usr/src/app

CMD ["yarn", "lint"]
