export const ADD_CLASSROOM_SUCCEEDED = 'ADD_CLASSROOM_SUCCEEDED';
export const GET_CLASSROOMS_SUCCEEDED = 'GET_CLASSROOMS_SUCCEEDED';
export const FLAG_GETTING_CLASSROOMS = 'FLAG_GETTING_CLASSROOMS';
export const FLAG_ADDING_CLASSROOM = 'FLAG_ADDING_CLASSROOM';
export const FLAG_DELETING_CLASSROOM = 'FLAG_DELETING_CLASSROOM';
export const DELETE_CLASSROOM_SUCCEEDED = 'DELETE_CLASSROOM_SUCCEEDED';
export const FLAG_EDITING_CLASSROOM = 'FLAG_EDITING_CLASSROOM';
export const EDIT_CLASSROOM_SUCCEEDED = 'EDIT_CLASSROOM_SUCCEEDED';
export const GET_CLASSROOM_SUCCEEDED = 'GET_CLASSROOM_SUCCEEDED';
export const FLAG_GETTING_CLASSROOM = 'FLAG_GETTING_CLASSROOM';
export const FLAG_ADDING_USER_IN_CLASSROOM = 'FLAG_ADDING_USER_IN_CLASSROOM';
export const FLAG_DELETING_USER_IN_CLASSROOM =
  'FLAG_DELETING_USER_IN_CLASSROOM';
export const FLAG_EDITING_USER_IN_CLASSROOM = 'FLAG_EDITING_USER_IN_CLASSROOM';
