export const ADD_CLASSROOM_SUCCEEDED = 'ADD_CLASSROOM_SUCCEEDED';
export const GET_CLASSROOMS_SUCCEEDED = 'GET_CLASSROOMS_SUCCEEDED';
export const FLAG_GETTING_CLASSROOMS = 'FLAG_GETTING_CLASSROOMS';
export const FLAG_ADDING_CLASSROOM = 'FLAG_ADDING_CLASSROOM';
export const FLAG_DELETING_CLASSROOM = 'FLAG_DELETING_CLASSROOM';
export const DELETE_CLASSROOM_SUCCEEDED = 'DELETE_CLASSROOM_SUCCEEDED';
export const FLAG_EDITING_CLASSROOM = 'FLAG_EDITING_CLASSROOM';
export const EDIT_CLASSROOM_SUCCEEDED = 'EDIT_CLASSROOM_SUCCEEDED';
export const GET_CLASSROOM_SUCCEEDED = 'GET_CLASSROOM_SUCCEEDED';
export const FLAG_GETTING_CLASSROOM = 'FLAG_GETTING_CLASSROOM';
export const FLAG_ADDING_USER_IN_CLASSROOM = 'FLAG_ADDING_USER_IN_CLASSROOM';
export const FLAG_DELETING_USERS_IN_CLASSROOM =
  'FLAG_DELETING_USERS_IN_CLASSROOM';
export const FLAG_EDITING_USER_IN_CLASSROOM = 'FLAG_EDITING_USER_IN_CLASSROOM';
export const FLAG_GETTING_SPACE_IN_CLASSROOM =
  'FLAG_GETTING_SPACE_IN_CLASSROOM';
export const GET_SPACE_IN_CLASSROOM_SUCCEEDED =
  'GET_SPACE_IN_CLASSROOM_SUCCEEDED';
export const FLAG_EXTRACTING_FILE_TO_LOAD_SPACE_IN_CLASSROOM =
  'FLAG_EXTRACTING_FILE_TO_LOAD_SPACE_IN_CLASSROOM';
export const EXTRACT_FILE_TO_LOAD_SPACE_IN_CLASSROOM_SUCCEEDED =
  'EXTRACT_FILE_TO_LOAD_SPACE_IN_CLASSROOM_SUCCEEDED';
export const LOAD_SPACE_IN_CLASSROOM_SUCCEEDED =
  'LOAD_SPACE_IN_CLASSROOM_SUCCEEDED';
export const CLEAR_LOAD_SPACE_IN_CLASSROOM_SUCCEEDED =
  'CLEAR_LOAD_SPACE_IN_CLASSROOM_SUCCEEDED';
export const FLAG_CLEARING_LOAD_SPACE_IN_CLASSROOM =
  'FLAG_CLEARING_LOAD_SPACE_IN_CLASSROOM';
export const FLAG_LOADING_SPACE_IN_CLASSROOM =
  'FLAG_LOADING_SPACE_IN_CLASSROOM';
export const GET_SPACE_TO_LOAD_IN_CLASSROOM_SUCCEEDED =
  'GET_SPACE_TO_LOAD_IN_CLASSROOM_SUCCEEDED';
export const FLAG_GETTING_SPACE_TO_LOAD_IN_CLASSROOM =
  'FLAG_GETTING_SPACE_TO_LOAD_IN_CLASSROOM';
