export const EXPORT_SPACE_SUCCESS = 'EXPORT_SPACE_SUCCESS';
export const FLAG_EXPORTING_SPACE = 'FLAG_EXPORTING_SPACES';
export const FLAG_CLEARING_EXPORT_SPACE = 'FLAG_CLEARING_EXPORT_SPACE';
export const CLEAR_EXPORT_SPACE = 'CLEAR_EXPORT_SPACE';
export const SET_EXPORT_SPACE = 'SET_EXPORT_SPACE';
export const FLAG_SETTING_EXPORT_SPACE = 'FLAG_SETTING_EXPORT_SPACE';
