export const POST_FILE = 'POST_FILE';
export const POST_FILE_SUCCEEDED = 'POST_FILE_SUCCEEDED';
export const POST_FILE_FAILED = 'POST_FILE_FAILED';

export const FILE_TYPES = [POST_FILE, POST_FILE_SUCCEEDED, POST_FILE_FAILED];
