export const LOAD_SPACE_SUCCEEDED = 'LOAD_SPACE_SUCCEEDED';
export const FLAG_EXTRACTING_FILE_TO_LOAD_SPACE =
  'FLAG_EXTRACTING_FILE_TO_LOAD_SPACE';
export const FLAG_CLEARING_LOAD_SPACE = 'FLAG_CLEARING_LOAD_SPACE';
export const CLEAR_LOAD_SPACE = 'CLEAR_LOAD_SPACE';
export const CLEAR_LOAD_SPACE_SUCCEEDED = 'CLEAR_LOAD_SPACE_SUCCEEDED';
export const FLAG_LOADING_SPACE = 'FLAG_LOADING_SPACE';
export const EXTRACT_FILE_TO_LOAD_SPACE_SUCCEEDED =
  'EXTRACT_FILE_TO_LOAD_SPACE_SUCCEEDED';
export const FLAG_GETTING_SPACE_TO_LOAD_SPACE =
  'FLAG_GETTING_SPACE_TO_LOAD_SPACE';
export const GET_SPACE_TO_LOAD_SPACE_SUCCEEDED =
  'GET_SPACE_TO_LOAD_SPACE_SUCCEEDED';
