export const LOAD_SPACE_SUCCEEDED = 'LOAD_SPACE_SUCCEEDED';
export const FLAG_EXTRACTING_FILE_TO_LOAD_SPACE =
  'FLAG_EXTRACTING_FILE_TO_LOAD_SPACE';
export const FLAG_CANCELING_TO_LOAD_SPACE = 'FLAG_CANCELING_TO_LOAD_SPACE';
export const CANCEL_LOAD_SPACE = 'CANCEL_LOAD_SPACE';
export const CANCEL_LOAD_SPACE_SUCCEEDED = 'CANCEL_LOAD_SPACE_SUCCEEDED';
export const FLAG_LOADING_SPACE = 'FLAG_LOADING_SPACE';
export const EXTRACT_FILE_TO_LOAD_SPACE_SUCCEEDED =
  'EXTRACT_FILE_TO_LOAD_SPACE_SUCCEEDED';
