export const GET_SPACES = 'GET_SPACES';
export const FLAG_GETTING_SPACE = 'FLAG_GETTING_SPACE';
export const FLAG_GETTING_SPACES = 'FLAG_GETTING_SPACES';
export const FLAG_DELETING_SPACE = 'FLAG_DELETING_SPACE';
export const TOGGLE_SPACE_MENU = 'TOGGLE_SPACE_MENU';
export const CLEAR_SPACE = 'CLEAR_SPACE';
export const GET_SPACE_SUCCEEDED = 'GET_SPACE_SUCCEEDED';
export const DELETE_SPACE_SUCCESS = 'DELETE_SPACE_SUCCESS';
export const FLAG_SAVING_SPACE = 'FLAG_SAVING_SPACE';
export const SAVE_SPACE_SUCCEEDED = 'SAVE_SPACE_SUCCEEDED';
export const FLAG_GETTING_SPACES_NEARBY = 'FLAG_GETTING_SPACES_NEARBY';
export const GET_SPACES_NEARBY_SUCCEEDED = 'GET_SPACES_NEARBY_SUCCEEDED';
export const FLAG_SYNCING_SPACE = 'FLAG_SYNCING_SPACE';
export const SYNC_SPACE_SUCCEEDED = 'SYNC_SPACE_SUCCEEDED';
export const FLAG_CLEARING_USER_INPUT = 'FLAG_CLEARING_USER_INPUT';
export const CLEAR_USER_INPUT_SUCCEEDED = 'CLEAR_USER_INPUT_SUCCEEDED';
export const SET_SPACE_SEARCH_QUERY_SUCCEEDED =
  'SET_SPACE_SEARCH_QUERY_SUCCEEDED';
