export const GET_SYNC_REMOTE_SPACE_SUCCEEDED =
  'GET_SYNC_REMOTE_SPACE_SUCCEEDED';
export const GET_SYNC_LOCAL_SPACE_SUCCEEDED = 'GET_SYNC_LOCAL_SPACE_SUCCEEDED';
export const CLEAR_SYNC_SPACES = 'CLEAR_SYNC_SPACES';
