export const GET_SYNC_REMOTE_SPACE_SUCCEEDED =
  'GET_SYNC_REMOTE_SPACE_SUCCEEDED';
export const GET_SYNC_LOCAL_SPACE_SUCCEEDED = 'GET_SYNC_LOCAL_SPACE_SUCCEEDED';
export const CLEAR_SYNC_SPACES = 'CLEAR_SYNC_SPACES';
export const SELECT_SYNC_PHASE = 'SELECT_SYNC_PHASE';
export const CLEAR_SYNC_PHASES = 'CLEAR_SYNC_PHASES';
export const FLAG_GETTING_SYNC_REMOTE_SPACE = 'FLAG_GETTING_SYNC_REMOTE_SPACE';
export const FLAG_GETTING_SYNC_LOCAL_SPACE = 'FLAG_GETTING_SYNC_LOCAL_SPACE';
