export const NEXT_OR_PREV_TOUR = 'NEXT_OR_PREV_TOUR';
export const NAVIGATE_STOP_TOUR = 'NAVIGATE_STOP_TOUR';
export const STOP_TOUR = 'STOP_TOUR';
export const RESTART_TOUR = 'RESTART_TOUR';
export const START_TOUR = 'START_TOUR';
export const RESET_TOUR = 'RESET_TOUR';
export const INITIALIZE_TOUR = 'INITIALIZE_TOUR';
