export const NEXT_TOUR_STEP = 'NEXT_TOUR_STEP';
export const PREV_TOUR_STEP = 'PREV_TOUR_STEP';
export const STOP_TOUR_AND_NAVIGATE = 'STOP_TOUR_AND_NAVIGATE';
export const STOP_TOUR = 'STOP_TOUR';
export const RESTART_TOUR = 'RESTART_TOUR';
export const START_TOUR = 'START_TOUR';
export const RESET_TOUR = 'RESET_TOUR';
export const INITIALIZE_TOUR = 'INITIALIZE_TOUR';
