export const GET_GEOLOCATION_SUCCEEDED = 'GET_GEOLOCATION_SUCCEEDED';
export const FLAG_GETTING_USER_FOLDER = 'FLAG_GETTING_USER_FOLDER';
export const GET_USER_FOLDER_SUCCEEDED = 'GET_USER_FOLDER_SUCCEEDED';
export const GET_LANGUAGE_SUCCEEDED = 'GET_LANGUAGE_SUCCEEDED';
export const SET_LANGUAGE_SUCCEEDED = 'SET_LANGUAGE_SUCCEEDED';
export const FLAG_GETTING_LANGUAGE = 'FLAG_GETTING_LANGUAGE';
export const FLAG_SETTING_LANGUAGE = 'FLAG_SETTING_LANGUAGE';
export const FLAG_GETTING_DEVELOPER_MODE = 'FLAG_GETTING_DEVELOPER_MODE';
export const FLAG_SETTING_DEVELOPER_MODE = 'FLAG_SETTING_DEVELOPER_MODE';
export const GET_DEVELOPER_MODE_SUCCEEDED = 'GET_DEVELOPER_MODE_SUCCEEDED';
export const SET_DEVELOPER_MODE_SUCCEEDED = 'SET_DEVELOPER_MODE_SUCCEEDED';
export const FLAG_GETTING_GEOLOCATION_ENABLED =
  'FLAG_GETTING_GEOLOCATION_ENABLED';
export const FLAG_SETTING_GEOLOCATION_ENABLED =
  'FLAG_SETTING_GEOLOCATION_ENABLED';
export const GET_GEOLOCATION_ENABLED_SUCCEEDED =
  'GET_GEOLOCATION_ENABLED_SUCCEEDED';
export const SET_GEOLOCATION_ENABLED_SUCCEEDED =
  'SET_GEOLOCATION_ENABLED_SUCCEEDED';

export const FLAG_GETTING_SYNC_MODE = 'FLAG_GETTING_SYNC_MODE';
export const FLAG_SETTING_SYNC_MODE = 'FLAG_SETTING_SYNC_MODE';
export const SET_SYNC_MODE_SUCCEEDED = 'SET_SYNC_MODE_SUCCEEDED';
export const GET_SYNC_MODE_SUCCEEDED = 'GET_SYNC_MODE_SUCCEEDED';
export const FLAG_GETTING_STUDENT_MODE = 'FLAG_GETTING_STUDENT_MODE';
export const FLAG_SETTING_STUDENT_MODE = 'FLAG_SETTING_STUDENT_MODE';
export const SET_STUDENT_MODE_SUCCEEDED = 'SET_STUDENT_MODE_SUCCEEDED';
export const GET_STUDENT_MODE_SUCCEEDED = 'GET_STUDENT_MODE_SUCCEEDED';
