export const GET_GEOLOCATION_SUCCEEDED = 'GET_GEOLOCATION_SUCCEEDED';
export const FLAG_GETTING_USER_FOLDER = 'FLAG_GETTING_USER_FOLDER';
export const GET_USER_FOLDER_SUCCEEDED = 'GET_USER_FOLDER_SUCCEEDED';
export const GET_LANGUAGE_SUCCEEDED = 'GET_LANGUAGE_SUCCEEDED';
export const SET_LANGUAGE_SUCCEEDED = 'SET_LANGUAGE_SUCCEEDED';
export const FLAG_GETTING_LANGUAGE = 'FLAG_GETTING_LANGUAGE';
export const FLAG_SETTING_LANGUAGE = 'FLAG_SETTING_LANGUAGE';
export const FLAG_GETTING_DEVELOPER_MODE = 'FLAG_GETTING_DEVELOPER_MODE';
export const FLAG_SETTING_DEVELOPER_MODE = 'FLAG_SETTING_DEVELOPER_MODE';
export const GET_DEVELOPER_MODE_SUCCEEDED = 'GET_DEVELOPER_MODE_SUCCEEDED';
export const SET_DEVELOPER_MODE_SUCCEEDED = 'SET_DEVELOPER_MODE_SUCCEEDED';
export const FLAG_GETTING_GEOLOCATION_ENABLED =
  'FLAG_GETTING_GEOLOCATION_ENABLED';
export const FLAG_SETTING_GEOLOCATION_ENABLED =
  'FLAG_SETTING_GEOLOCATION_ENABLED';
export const GET_GEOLOCATION_ENABLED_SUCCEEDED =
  'GET_GEOLOCATION_ENABLED_SUCCEEDED';
export const SET_GEOLOCATION_ENABLED_SUCCEEDED =
  'SET_GEOLOCATION_ENABLED_SUCCEEDED';
export const FLAG_GETTING_SYNC_MODE = 'FLAG_GETTING_SYNC_MODE';
export const FLAG_SETTING_SYNC_MODE = 'FLAG_SETTING_SYNC_MODE';
export const SET_SYNC_MODE_SUCCEEDED = 'SET_SYNC_MODE_SUCCEEDED';
export const GET_SYNC_MODE_SUCCEEDED = 'GET_SYNC_MODE_SUCCEEDED';
export const FLAG_GETTING_USER_MODE = 'FLAG_GETTING_USER_MODE';
export const FLAG_SETTING_USER_MODE = 'FLAG_SETTING_USER_MODE';
export const SET_USER_MODE_SUCCEEDED = 'SET_USER_MODE_SUCCEEDED';
export const GET_USER_MODE_SUCCEEDED = 'GET_USER_MODE_SUCCEEDED';
export const SET_SYNC_MODES_SUCCEEDED = 'SET_SYNC_MODES_SUCCEEDED';
export const GET_SYNC_MODES_SUCCEEDED = 'GET_SYNC_MODES_SUCCEEDED';
export const FLAG_SETTING_SPACE_AS_FAVORITE = 'FLAG_SETTING_SPACE_AS_FAVORITE';
export const SET_SPACE_AS_FAVORITE_SUCCEEDED =
  'SET_SPACE_AS_FAVORITE_SUCCEEDED';
export const FLAG_SETTING_SPACE_AS_RECENT = 'FLAG_SETTING_SPACE_AS_RECENT';
export const SET_SPACE_AS_RECENT = 'SET_SPACE_AS_RECENT';
export const SET_SPACE_AS_RECENT_SPACES_SUCCEEDED =
  'SET_SPACE_AS_RECENT_SPACES_SUCCEEDED';
export const FLAG_SETTING_ACTION_ACCESSIBILITY =
  'FLAG_SETTING_ACTION_ACCESSIBILITY';
export const SET_ACTION_ACCESSIBILITY_SUCCEEDED =
  'SET_ACTION_ACCESSIBILITY_SUCCEEDED';
export const FLAG_SETTING_ACTIONS_AS_ENABLED =
  'FLAG_SETTING_ACTIONS_AS_ENABLED';
export const SET_ACTIONS_AS_ENABLED_SUCCEEDED =
  'SET_ACTIONS_AS_ENABLED_SUCCEEDED';
export const FLAG_SETTING_FONT_SIZE = 'FLAG_SETTING_FONT_SIZE';
export const SET_FONT_SIZE_SUCCEEDED = 'SET_FONT_SIZE_SUCCEEDED';
export const GET_FONT_SIZE_SUCCEEDED = 'GET_FONT_SIZE_SUCCEEDED';
export const FLAG_GETTING_FONT_SIZE = 'FLAG_GETTING_FONT_SIZE';
