export const GET_GEOLOCATION_SUCCEEDED = 'GET_GEOLOCATION_SUCCEEDED';
export const FLAG_GETTING_USER_FOLDER = 'FLAG_GETTING_USER_FOLDER';
export const GET_USER_FOLDER_SUCCEEDED = 'GET_USER_FOLDER_SUCCEEDED';
export const GET_LANGUAGE_SUCCEEDED = 'GET_LANGUAGE_SUCCEEDED';
export const SET_LANGUAGE_SUCCEEDED = 'SET_LANGUAGE_SUCCEEDED';
export const FLAG_GETTING_LANGUAGE = 'FLAG_GETTING_LANGUAGE';
export const FLAG_SETTING_LANGUAGE = 'FLAG_SETTING_LANGUAGE';
